name = "notes-bynuno"
compatibility_date = "2026-02-20"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "notes-bynuno-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"

[vars]
APP_URL = "https://notes.bynuno.com"